# Generated by Django 5.0.4 on 2024-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
