# Generated by Django 5.0.3 on 2024-05-12 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
