# Generated by Django 5.0.4 on 2024-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_slug_alter_product_slug_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
