"""
Django settings for clothing_ecommerce project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v078ki*0#eas@r5zg4ez5%q^ys&1mod%)cdw_)pgumjw!9b4f-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
SESSION_COOKI_AGE = 1209600

CART_SESSION_ID = 'cart'
LOGIN_REDIRECT_URL = 'myaccount'
LOGOUT_REDIRECT_URL = 'frontpage'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'store',
    'userprofile',
    'django_extensions',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clothing_ecommerce.urls'
WEBSITE_URL = 'http://127.0.0.1:8000/'

STRIPE_PUBLIC_KEY = 'pk_test_51PEoUk04HuykUfrKyW3PCu4Mbtf5cLd8MBxfLW1ZuT8rZCtjwU4c5KJpCLkMjspk6wN7TD7fZ3IAOPky6XwuplHR00VhJFjDXj'
STRIPE_SECRET_KEY = 'sk_test_51PEoUk04HuykUfrKUP0tvHOyFeqH3PWM3dzOjIV8HHqqdJ6385NEK8LdCalf71uvxZeLEY3JiX7N5xTXzURNAkVO00xNKRGdtP'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clothing_ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'staticfiles/'
Media_URL = 'media/'
MEDIA_ROOT = BASE_DIR/'media'

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPH_MODELS ={
'all_applications': True,
'graph_models': True,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'itsfacelessmen@gmail.com'
EMAIL_HOST_PASSWORD = 'your_gmail_password'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'your_gmail_address@gmail.com'

JAZZMIN_SETTINGS = {
    # title of the window (Will show up in browser tab)
    "site_title": "YetiWears Admin",

    # Title on the login screen (19 chars max)
    "site_header": "YETIWEARS",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Clothing Ecommerce admin",

    # Copyright on the footer
    "copyright": "YetiWears Clothing Ecommerce",

    # The brand name of your site
    "brand_colour": "navbar-info",

    # An optional favicon
    "site_logo": "yeti.png",

    # Welcome image
    "welcome_image": "yeti.png",

    # Icons for side menu
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Category": "fas fa-list",
        "store.Product": "fas fa-shopping-bag",  
        "store.Order": "fas fa-cash-register",
        "store.OrderItem": "fas fa-list-alt",
    },

    # Custom links to append to app_list
    "custom_links": {
        "store": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
        }]
    },

    # Custom icons for model admins
    "icons": {
        "store.Category": "fas fa-sitemap",
        "store.Product": "fas fa-box",
        "store.Order": "fas fa-shopping-cart",
        "store.OrderItem": "fas fa-list-ul",
    },
}